const assert=require('node:assert/strict'),vm=require('node:vm');
const {Element,questions,script,setViewport}=require('./flow.cjs');
const key='associatieruimte.v01';
async function setup(routeId='landscape',viewport='desktop',saved){
 setViewport(viewport==='mobile'?350:872,viewport==='mobile'?380:500);
 const app=new Element('main'),erase=new Element('button'),notice=new Element('p'),storage={};
 storage[key]=JSON.stringify(saved||{step:1,stepId:'imagine',entryType:'Ik zit ergens mee',originalQuestion:'Een eigen beginvraag',answers:{},associations:[],routeId,imageIds:['image-01','image-02','image-03'],selectedImage:null,selectedElement:null,activeId:null,firstSpaceStep:null,research:null});
 let ctx={document:{querySelector:q=>({'#app':app,'#erase':erase,'#storage-notice':notice})[q],createElement:t=>new Element(t)},localStorage:{getItem:k=>storage[k]??null,setItem:(k,v)=>storage[k]=v,removeItem:k=>delete storage[k]},crypto:require('node:crypto').webcrypto,window:{scrollTo(){}},fetch:async()=>({ok:true,json:async()=>questions})};
 const boot=async()=>{ctx={...ctx};vm.createContext(ctx);vm.runInContext(script,ctx);await new Promise(r=>setImmediate(r));};await boot();
 const state=()=>JSON.parse(storage[key]);
 const click=(text,host=app)=>{const b=host.querySelectorAll('button').find(n=>n.textContent===text||n.attrs['aria-label']===text);assert(b,'Button: '+text);b.listeners.click();};
 const form=taking=>app.querySelectorAll('form').find(n=>n.attrs['aria-label']===(taking?'Iets meenemen':'Zelf iets toevoegen'));
 const submit=(taking,text,color)=>{const f=form(taking);assert(f);const input=f.querySelectorAll('input').find(n=>n.attrs.type!=='color');input.value=text;if(color){const c=f.querySelectorAll('input').find(n=>n.attrs.type==='color');c.value=color;c.listeners.input();}f.listeners.submit({preventDefault(){}});};
 const answer=(index,text)=>{const n=app.querySelectorAll('textarea')[index];assert(n);n.value=text;n.listeners.input();};
 return{app,state,click,form,submit,answer,boot,storage,get ctx(){return ctx;}};
}
const options=h=>h.app.querySelectorAll('.answer-chip');
const option=(h,text)=>options(h).find(n=>n.querySelector('.answer-chip-text').textContent===text);
const offered=h=>options(h).map(n=>n.querySelector('.answer-chip-text').textContent);
(async()=>{
 for(const viewport of ['desktop','mobile'])for(const route of questions.routes){
  const h=await setup(route.id,viewport);assert(h.app.querySelector('.answer-suggestions').hidden);assert(h.form(false));assert(!h.form(true));assert(!h.app.textContent.includes('Wat wil je meenemen?'));
  const raw='  stromend water $& <b>\n tweede regel  ',second='Een heel andere eigen associatie';h.answer(0,raw);h.answer(1,second);assert.deepEqual(offered(h),[raw,second]);assert.equal(h.state().associations.length,0);assert(h.app.textContent.includes('Dit zijn dingen die je eerder invulde:'));assert(h.app.textContent.includes('Wil je iets hiervan een plek geven in je Associatieruimte?'));assert(h.app.textContent.includes('Komt er nog iets anders bij je op?'));
  const first=option(h,raw);first.listeners.click();assert.equal(h.state().associations[0].text,raw);assert.equal(h.state().answers[route.fields[0].key],raw);assert(!('color' in h.state().associations[0]));assert.equal(option(h,raw).attrs.disabled,'');assert(option(h,raw).textContent.includes('Toegevoegd'));first.listeners.click();option(h,raw).listeners.click();assert.equal(h.state().associations.length,1,'Repeated/stale clicks must not duplicate');
  await h.boot();assert.equal(h.state().associations.length,1);assert.equal(option(h,raw).attrs.disabled,'');option(h,second).listeners.click();assert.equal(h.state().associations.length,2);h.submit(false,'vrijheid','#2288cc');assert.equal(h.state().associations.length,3);assert.equal(h.state().associations.at(-1).text,'vrijheid');assert.equal(h.state().associations.at(-1).color,'#2288cc');assert.equal(h.state().answers[route.fields[1].key],second);assert(!Object.values(h.state().answers).some(a=>a.includes('vrijheid')));
  assert.deepEqual(Object.keys(h.state().associations[0]).sort(),Object.keys(h.state().associations[1]).sort());assert(!Object.keys(h.state().associations[0]).some(k=>/source|category|meaning/.test(k)));
  h.click('Verder');h.click('Kies beeld 1');h.answer(0,'Mijn beeldantwoord');assert.deepEqual(offered(h),[raw,second,'Mijn beeldantwoord']);option(h,'Mijn beeldantwoord').listeners.click();assert.equal(h.state().associations.length,4);h.click('Verder');assert.equal(h.app.querySelector('h1').textContent,'Jouw Associatieruimte');assert(option(h,raw));
  for(const text of [raw,'vrijheid']){const word=h.app.querySelectorAll('.word').find(n=>n.textContent===text);assert(word);word.listeners.click();const size=parseFloat(word.style.fontSize);h.click('Groter');assert(parseFloat(word.style.fontSize)>size);h.click('Kleiner');const left=parseFloat(word.style.left);h.click('→');assert(parseFloat(word.style.left)>left);word.listeners.pointerdown({button:0,clientX:100,clientY:100,pointerId:1});const start=parseFloat(word.style.left);word.listeners.pointermove({clientX:120,clientY:115});assert(parseFloat(word.style.left)>start);word.listeners.pointerup();const color=h.app.querySelectorAll('input').find(n=>n.attrs['aria-label']==='Kleur van geselecteerd element');color.value='#112233';color.listeners.input();assert.equal(word.style.backgroundColor,'#112233');}
  h.click('Verder');assert.equal(h.app.querySelector('.choices').querySelectorAll('button').length,3);await h.boot();assert.equal(h.state().associations.length,4);
 }
 for(const viewport of ['desktop','mobile']){
  const skip=await setup('landscape',viewport);skip.answer(0,'Niets verplicht');skip.click('Verder');skip.click('Verder');assert.equal(skip.app.querySelector('h1').textContent,'Terug naar je beginvraag');assert(!skip.app.querySelector('select'));skip.click('Verder');skip.click('Verder');assert.equal(skip.app.querySelector('h1').textContent,'Dit ontstond er onderweg');assert.equal(skip.state().associations.length,0);
  const one=await setup('animal',viewport);one.answer(0,'egel');option(one,'egel').listeners.click();one.click('Verder');one.click('Verder');one.click('Verder');assert.equal(one.app.querySelector('.choices').querySelectorAll('button').length,2);
  const duplicate=await setup('movement',viewport);duplicate.answer(0,'Hetzelfde antwoord');duplicate.answer(1,'Hetzelfde antwoord');assert.deepEqual(offered(duplicate),['Hetzelfde antwoord']);duplicate.submit(false,'Hetzelfde antwoord');assert.equal(option(duplicate,'Hetzelfde antwoord').attrs.disabled,'');await duplicate.boot();assert.equal(duplicate.state().associations.length,1);
 }
 const long='Een volledig letterlijk antwoord\n'+'woord '.repeat(250);const legacy={step:3,stepId:'space',entryType:'Ik zit ergens mee',originalQuestion:'Niet aanbieden',answers:{landscape:long,notice:'Mijn waarneming',other:'Nog iets',animal:'Andere route niet aanbieden',imageAssociation:'Eigen beeldantwoord',imageTogether:'Nog een beeldantwoord',reflection:'Geen reflectie aanbieden',memory:'Niet gebruiken',unknown:'Geen onbekende velden'},associations:[{id:'old',text:long,x:35,y:40,size:1.3,color:'#112233'},{id:'shape',shape:'circle',text:'',x:50,y:50,size:1,color:'#445566'}],routeId:'landscape',imageIds:['image-01','image-02','image-03']};
 const resumed=await setup('landscape','mobile',legacy);assert.deepEqual(offered(resumed),[long,'Mijn waarneming','Nog iets','Eigen beeldantwoord','Nog een beeldantwoord']);assert.equal(option(resumed,long).attrs.disabled,'');assert.deepEqual(resumed.state().answers,legacy.answers);assert.equal(resumed.state().associations.length,2);assert.equal(option(resumed,long).querySelector('.answer-chip-text').textContent,long);assert(resumed.form(false));
 const css=require('fs').readFileSync(require('path').join(__dirname,'../styles.css'),'utf8');assert(css.includes('max-height:16rem;overflow:auto'));assert(css.includes('white-space:pre-wrap;overflow-wrap:anywhere'));assert(css.includes('.collect-word{flex-direction:column}'));
 console.log('PASS answer chips: all active routes and images; literal/own/explicitly allowed fields only; multiple clicks, stale-click dedup, added status, free additions, canvas color/size/position/drag, 0/1/2+ rules, long answers, responsive rules, reload and old sessions on desktop/mobile');
})().catch(e=>{console.error(e);process.exitCode=1;});
