const fs=require('fs'),vm=require('vm'),assert=require('assert'),path=require('path');
const root=path.resolve(__dirname,'..');
let width=350,height=380;
class Element{
 constructor(tag){this.tag=tag;this.children=[];this.attrs={};this.listeners={};this.style={};this.dataset={};this.value='';this._text='';}
 set textContent(t){this._text=t;this.children=[];}get textContent(){return this._text+this.children.map(c=>c.textContent).join('');}
 setAttribute(k,v){this.attrs[k]=String(v);}getAttribute(k){return this.attrs[k];}
 append(...c){this.children.push(...c);for(const n of c)n.parent=this;}
 replaceChildren(...c){this.children=[];this._text='';this.append(...c);}
 addEventListener(k,fn){this.listeners[k]=fn;}
 remove(){if(this.parent)this.parent.children=this.parent.children.filter(n=>n!==this);this.parent=null;}
 querySelectorAll(q){return this.children.flatMap(c=>[...(match(c,q)?[c]:[]),...c.querySelectorAll(q)]);}
 querySelector(q){return this.querySelectorAll(q)[0];}focus(){}before(n){this.parent.children.splice(this.parent.children.indexOf(this),0,n);}setPointerCapture(id){this.capturedPointer=id;}
 getBoundingClientRect(){return {width,height};}get offsetWidth(){return parseFloat(this.style.width)||Math.min(width*.65,140);}get offsetHeight(){return parseFloat(this.style.height)||44;}
}
function match(n,q){return q.startsWith('.')?(n.attrs.class||'').split(' ').includes(q.slice(1)):q==='[aria-pressed="true"]'?n.attrs['aria-pressed']==='true':n.tag===q;}
const script=fs.readFileSync(path.join(root,'app.js'),'utf8'), questions=JSON.parse(fs.readFileSync(path.join(root,'questions.json')));
async function scenario(count,late=false,viewport='mobile',configured=true,routeIndex=0){
 // Exercise the real configured destinations without mutating the content.
 assert.equal(questions.contactLinks.experience,'mailto:info@jekerntotbloei.nl?subject=Mijn%20ervaring%20met%20de%20Associatieruimte');assert.equal(questions.contactLinks.introduction,'https://www.jekerntotbloei.nl/afspraak-maken');
 width=viewport==='mobile'?350:872;height=viewport==='mobile'?380:500;
 const app=new Element('main'),erase=new Element('button'),notice=new Element('p');let stored=null;const requests=[];const storage={};
 const math=Object.create(Math);math.random=()=> (routeIndex+.1)/3;
 const ctx={Math:math,document:{querySelector:q=>({'#app':app,'#erase':erase,'#storage-notice':notice})[q],createElement:t=>new Element(t)},localStorage:{getItem:k=>storage[k]??null,setItem:(k,v)=>{storage[k]=v;if(k==='associatieruimte.v01')stored=v;},removeItem:k=>{delete storage[k];if(k==='associatieruimte.v01')stored=null;}},crypto:require('crypto').webcrypto,window:{scrollTo(){}},ResizeObserver:class{observe(){}disconnect(){}},fetch:async url=>{requests.push(url);return{ok:true,json:async()=>questions};}};
 vm.createContext(ctx);vm.runInContext(script,ctx);await new Promise(r=>setImmediate(r));
 const click=text=>{const n=app.querySelectorAll('button').find(n=>n.textContent===text);assert(n,text);n.listeners.click();};
 const heading=()=>app.querySelector('h1').textContent;
 const add=text=>{app.querySelectorAll('input').find(n=>n.attrs['aria-label']==='Nieuw woord of korte zin').value=text;app.querySelector('form').listeners.submit({preventDefault(){}});};
 click('Ik zit ergens mee');const original='  Mijn vraag <script>\n exact  ';const question=app.querySelector('textarea');question.value=original;question.listeners.input();click('Verder');
 assert.equal(JSON.parse(stored).routeId,questions.routes[routeIndex].id);assert.deepEqual(app.querySelectorAll('textarea').map(n=>n.attrs['aria-label']),questions.routes[routeIndex].fields.map(f=>f.text));const initialChoices={routeId:JSON.parse(stored).routeId,imageIds:JSON.parse(stored).imageIds};
 const landscape=app.querySelector('textarea');landscape.value='Een landschap zonder toegevoegde woorden';landscape.listeners.input();assert.equal(JSON.parse(stored).associations.length,0,'Answers must never add elements automatically');assert.equal(app.querySelector('.answer-reference').textContent,'(Eerder schreef je: ‘Een landschap zonder toegevoegde woorden’)');for(let i=0;i<count;i++){if(i===0){const c=app.querySelectorAll('input').find(n=>n.attrs['aria-label']==='Kleur voor nieuw woord of korte zin');c.value='#8844aa';c.listeners.input();}add(i===0?'vogeltje $&':`woord ${i}`);}if(count){assert.equal(JSON.parse(stored).associations[0].color,'#8844aa');assert.equal(app.querySelector('.cloud-word').style.backgroundColor,'#8844aa');assert(!app.querySelector('.cloud-word').listeners.pointerdown);if(count>1)assert(!('color' in JSON.parse(stored).associations[1]));}
 click('Verder');assert.equal(app.querySelectorAll('img').length,3);assert(app.querySelectorAll('img').every(n=>n.attrs.src.startsWith('images/candidates/')));const sources=app.querySelectorAll('img').map(n=>n.attrs.src);click('Terug');assert.equal(JSON.parse(stored).routeId,initialChoices.routeId);click('Verder');assert.deepEqual(app.querySelectorAll('img').map(n=>n.attrs.src),sources);app.querySelectorAll('button').find(n=>n.attrs['aria-label']==='Kies beeld 1').listeners.click();assert.equal(app.querySelector('.answer-reference').textContent,'(Eerder schreef je: ‘Een landschap zonder toegevoegde woorden’)');click('Verder');
 if(count>=1){assert.equal(heading(),'Jouw Associatieruimte');assert(!app.querySelectorAll('button').some(n=>n.textContent==='Kleurvlek toevoegen'));assert(app.querySelector('.intro').textContent.includes('Er is inmiddels'));assert(!app.querySelectorAll('button').some(n=>/Cirkel toevoegen|Rechthoek toevoegen|Kleurvlek toevoegen/.test(n.textContent)));const word=app.querySelector('.word');assert.equal(word.style.backgroundColor,'#8844aa');word.listeners.click();assert.equal(word.attrs['aria-pressed'],'true');for(const name of ['Groter','Kleiner','←','→','↑','↓','Verwijderen'])assert(app.querySelectorAll('button').some(n=>n.textContent===name),'Missing control: '+name);const font=parseFloat(word.style.fontSize);click('Groter');assert(parseFloat(word.style.fontSize)>font);click('Kleiner');assert(Math.abs(parseFloat(word.style.fontSize)-font)<1e-9);const initialLeft=parseFloat(word.style.left),initialTop=parseFloat(word.style.top);click('→');assert(parseFloat(word.style.left)>initialLeft);click('←');assert(Math.abs(parseFloat(word.style.left)-initialLeft)<1e-9);click('↓');assert(parseFloat(word.style.top)>initialTop);click('↑');assert(Math.abs(parseFloat(word.style.top)-initialTop)<1e-9);word.listeners.keydown({key:'ArrowRight',preventDefault(){}});assert(parseFloat(word.style.left)>initialLeft);word.listeners.pointerdown({button:0,clientX:100,clientY:100,pointerId:1,preventDefault(){}});assert.equal(word.capturedPointer,1);assert.equal(word.attrs['aria-pressed'],'true');const wordLeft=parseFloat(word.style.left),wordTop=parseFloat(word.style.top);word.listeners.pointermove({clientX:140,clientY:120});assert(parseFloat(word.style.left)>wordLeft,'Word must visibly move before pointerup');assert(parseFloat(word.style.top)>wordTop);word.listeners.pointerup();assert(JSON.parse(stored).associations[0].x>20);word.listeners.click();const color=app.querySelectorAll('input').find(n=>n.attrs.type==='color');color.value='#be4466';color.listeners.input();assert.equal(JSON.parse(stored).associations[0].color,'#be4466');word.listeners.pointerdown({button:0,clientX:100,clientY:100,pointerId:2});word.listeners.pointermove({clientX:99999,clientY:99999});word.listeners.pointerup();assert(parseFloat(word.style.left)+word.offsetWidth/2/width*100<=100);assert(parseFloat(word.style.top)+word.offsetHeight/2/height*100<=100);
  for(const name of ['Cirkel','Rechthoek']){vm.runInContext("state.associations.push({id:crypto.randomUUID(),shape:'"+(name==='Cirkel'?'circle':'rectangle')+"',text:'',x:50,y:50,size:1,color:'#b3c5bb'});state.activeId=state.associations.at(-1).id;save();render();",ctx);const shape=app.querySelectorAll('.shape').at(-1);assert(shape);const previous=JSON.parse(stored).associations.at(-1);click('→');click('Groter');const changed=JSON.parse(stored).associations.at(-1);assert(changed.x>previous.x&&changed.size>previous.size);shape.listeners.pointerdown({button:0,clientX:100,clientY:100,pointerId:1,pointerType:viewport==='mobile'?'touch':'mouse',preventDefault(){}});assert.equal(shape.capturedPointer,1);const shapeLeft=parseFloat(shape.style.left);shape.listeners.pointermove({clientX:150,clientY:130});assert(parseFloat(shape.style.left)>shapeLeft,'Shape must visibly move before pointerup');shape.listeners.pointerup();assert(JSON.parse(stored).associations.at(-1).x>changed.x);const c=app.querySelectorAll('input').find(n=>n.attrs.type==='color');c.value='#2288cc';c.listeners.input();assert.equal(JSON.parse(stored).associations.at(-1).color,'#2288cc');click('Verwijderen');assert.equal(app.querySelectorAll('.shape').length,0);}
  const optionalColor=app.querySelectorAll('input').find(n=>n.attrs['aria-label']==='Kleur voor nieuw woord of korte zin');optionalColor.value='#112233';optionalColor.listeners.input();click('Geen specifieke kleur');add('tijdelijk woord');assert(!('color' in JSON.parse(stored).associations.at(-1))); click('tijdelijk woord');click('Verwijderen');assert(!app.querySelectorAll('.word').some(n=>n.textContent==='tijdelijk woord'));click('Verder');
 }else if(count>0){assert.equal(heading(),'Sta bij één element stil');assert(!app.querySelector('.canvas'));}else{assert.equal(heading(),'Nog één ding…');assert(!app.querySelector('select'));}
 if(count){assert.equal(heading(),'Wil je eens iets uitproberen?');assert.equal(app.querySelector('.choices').querySelectorAll('button').length,count===1?2:3);assert.equal(JSON.parse(stored).research.routeId,null);assert(!app.querySelector('.collector'));click('Verder');}
 if(late){for(let i=count;i<1;i++)add('later '+i);}
 if(count>=1||late){assert.equal(heading(),'Kijk opnieuw naar je ruimte');assert(!app.querySelector('select'));assert(!app.querySelector('textarea'));if(late&&count<1)assert(app.querySelector('.intro').textContent.includes('Er is inmiddels'));vm.runInContext("state.associations.push({id:crypto.randomUUID(),shape:'circle',text:'',x:50,y:50,size:1,color:'#b3c5bb'});state.activeId=state.associations.at(-1).id;save();render();",ctx);const c=app.querySelectorAll('input').find(n=>n.attrs.type==='color');c.value='#cc6633';c.listeners.input();click('Verder');}
 assert.equal(heading(),'Nog één ding…');assert(app.querySelector('.canvas'));assert(!app.textContent.includes(original));click('Verder');click('Verder');click('Verder');assert.equal(heading(),'Terug naar je beginvraag');assert(app.textContent.includes('Terugblik · niet bewerkbaar'));assert(app.textContent.includes('Dit is je Associatieruimte zoals die nu is ontstaan.'));assert(!app.querySelector('.tools'));assert(app.querySelectorAll('.word').every(n=>n.tag==='span'));assert.equal(app.querySelector('blockquote').textContent,original);const reflection=app.querySelector('textarea');reflection.value='Mijn eigen letterlijke opbrengst $&';reflection.listeners.input();click('Verder');const newQuestion=app.querySelector('textarea');newQuestion.value='Mijn eigen letterlijke vraag?';newQuestion.listeners.input();click('Verder');assert(app.querySelectorAll('h2').some(n=>n.textContent==='Wat je zelf meenam'));assert(app.querySelectorAll('h2').some(n=>n.textContent==='Een vraag die ontstond'));assert(app.querySelectorAll('.literal').some(n=>n.textContent==='Mijn eigen letterlijke opbrengst $&'));assert(app.querySelectorAll('.literal').some(n=>n.textContent==='Mijn eigen letterlijke vraag?'));assert(!app.textContent.includes('Je eigen slottekst'));assert(!app.textContent.includes('Je nieuwe vraag'));assert.equal(heading(),'Dit ontstond er onderweg');assert(app.textContent.includes('Terugblik · niet bewerkbaar'));assert(!app.querySelector('.tools'));for(const label of ['Deel je ervaring met mij','Kennismaken']){const b=app.querySelectorAll('button').find(n=>n.textContent===label);if(configured){const a=app.querySelectorAll('a').find(n=>n.textContent===label);assert(a);assert(!a.attrs.href.includes(original));assert.equal(a.attrs.href,questions.contactLinks[label==='Kennismaken'?'introduction':'experience']);}else assert(b&&b.attrs['aria-disabled']==='true');}if(count>=1||late){assert.equal(app.querySelectorAll('.shape').length,1);assert.equal(JSON.parse(stored).associations.at(-1).color,'#cc6633');}assert.deepEqual(requests,['questions.json']);
 // Re-execute with the same localStorage to verify resumed session.
 vm.createContext({...ctx});vm.runInNewContext(script,{...ctx});await new Promise(r=>setImmediate(r));assert.equal(heading(),'Dit ontstond er onderweg');assert.deepEqual(JSON.parse(stored).imageIds,initialChoices.imageIds);assert.equal(JSON.parse(stored).routeId,initialChoices.routeId);erase.listeners.click();assert.notEqual(JSON.parse(stored).routeId,initialChoices.routeId);assert.notEqual([...JSON.parse(stored).imageIds].sort().join('|'),[...initialChoices.imageIds].sort().join('|'));assert.equal(heading(),'Waar wil je even bij stilstaan?');
 const legacy={step:3,entryType:'Ik zit ergens mee',originalQuestion:'oud',answers:{landscape:'bewaard'},associations:[{id:'old-shape',shape:'blob',text:'',x:50,y:50,size:1,color:'#aabbcc'}],selectedImage:1};storage['associatieruimte.v01']=JSON.stringify(legacy);vm.runInNewContext(script,{...ctx});await new Promise(r=>setImmediate(r));assert.equal(JSON.parse(stored).routeId,'landscape');assert.equal(JSON.parse(stored).answers.landscape,'bewaard');assert.equal(JSON.parse(stored).associations[0].id,'old-shape');assert.equal(heading(),'Nog één ding…');assert(!app.querySelector('select'));
 console.log(`PASS ${viewport}: ${count} initial words${late?', first word added later':''}; ${questions.routes[routeIndex].id}; full flow, stable choices, color, legacy shapes, resume, reset`);
}
module.exports={Element,questions,script,setViewport:(w,h)=>{width=w;height=h;}};
if(require.main===module)(async()=>{for(const viewport of ['desktop','mobile'])for(const routeIndex of [0,1,2])for(const [count,late] of [[0,false],[1,false],[2,false],[3,false],[5,false],[6,false]])await scenario(count,late,viewport,true,routeIndex);await scenario(0,false,'desktop',true);})();
