// Optional real Chromium checks; install Playwright + Chromium in the test environment.
const {chromium}=require('playwright'),assert=require('node:assert/strict'),http=require('node:http'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..'),key='associatieruimte.v01';
const server=http.createServer((req,res)=>{const file=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname);if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}fs.readFile(file,(err,data)=>{if(err){res.writeHead(404).end();return;}res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.json':'application/json','.css':'text/css','.webp':'image/webp'})[path.extname(file)]||'application/octet-stream');res.end(data);});});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;try{
 browser=await chromium.launch({args:['--no-sandbox']});const url=`http://127.0.0.1:${server.address().port}/index.html`;
 for(const mobile of [false,true])for(const mask of [0,1,2,3]){
  const context=await browser.newContext({viewport:mobile?{width:390,height:844}:{width:1280,height:900},hasTouch:mobile});
  await context.addInitScript(()=>{if(!localStorage.getItem('associatieruimte.v01'))localStorage.setItem('associatieruimte.v01',JSON.stringify({stepId:'object',flowVersion:3,objectFlowVersion:2,objectId:'touw',objectPhase:0,originalQuestion:'Vraag',answers:{},associations:[{id:'keep',text:'energie',x:30,y:40,size:1.3,color:'#123456'}],routeId:'animal',imageIds:['image-01','image-02','image-03']}));});
  const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(url);
  const ready=()=>page.getByRole('heading',{name:'Nog één ding…',exact:true}).waitFor();await ready();
  const state=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('associatieruimte.v01')));
  const check=async phase=>{const s=await state();assert.equal(s.objectPhase,phase);assert.equal(s.stepId,'object');assert.equal(s.objectId,'touw');assert.equal(s.associations.length,1);await page.locator('.canvas .word[data-id="keep"]').waitFor({state:'visible'});assert(await page.getByText('Er verschijnt ineens een touw in je Associatieruimte.',{exact:true}).isVisible());assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));};
  const labels=['Wat zou je ermee doen?','Voer je bedachte actie in gedachten uit. Wat zie je?'],answers=['  Mijn actie $& <b>\n  ','  Mijn beeld\n  '];
  const refresh=async phase=>{const before=await state();await page.reload();await ready();await check(phase);assert.deepEqual((await state()).answers,before.answers);if(phase===0){assert.equal(await page.locator('textarea').count(),2);for(let i=0;i<2;i++)assert.equal(await page.getByRole('textbox',{name:labels[i],exact:true}).inputValue(),before.answers[i?'objectView':'objectAction']??'');}};
  await check(0);assert.equal(await page.locator('textarea').count(),2);await refresh(0);
  if(mask&1)await page.getByRole('textbox',{name:labels[0],exact:true}).fill(answers[0]);await refresh(0);
  if(mask&2)await page.getByRole('textbox',{name:labels[1],exact:true}).fill(answers[1]);await check(0);assert.equal(await page.getByRole('textbox',{name:labels[0],exact:true}).inputValue(),mask&1?answers[0]:'');await refresh(0);
  await page.getByRole('button',{name:'Verder',exact:true}).click();await check(1);assert.equal(await page.locator('textarea').count(),0);assert.equal(await page.locator('.answer-chip-text').count(),Boolean(mask&1)+Boolean(mask&2));await refresh(1);
  await page.getByRole('button',{name:'Terug',exact:true}).click();await check(0);await refresh(0);await page.getByRole('button',{name:'Verder',exact:true}).click();await check(1);await page.getByRole('button',{name:'Verder',exact:true}).click();await page.getByRole('heading',{name:'Terug naar je beginvraag',exact:true}).waitFor();await page.getByRole('button',{name:'Terug',exact:true}).click();await check(1);assert.deepEqual(errors,[]);await context.close();console.log(`PASS Chromium object: ${mobile?'mobile':'desktop'}, answer mask ${mask}, simultaneous fields, refresh, back, words`);
 }
 // Resume each old screen without changing words, object or literal answers.
 for(const oldPhase of [0,1,2]){
  const context=await browser.newContext({viewport:{width:390,height:844}});const page=await context.newPage();await page.goto(url);await page.evaluate(({key,oldPhase})=>localStorage.setItem(key,JSON.stringify({stepId:'object',flowVersion:3,objectId:'touw',objectPhase:oldPhase,originalQuestion:'Vraag',answers:{objectAction:'Mijn actie',objectView:'Mijn beeld'},associations:[{id:'keep',text:'energie',x:30,y:40,size:1}],routeId:'animal',imageIds:['image-01','image-02','image-03']})),{key,oldPhase});await page.reload();await page.getByRole('heading',{name:'Nog één ding…',exact:true}).waitFor();const expected=oldPhase===2?1:0;for(let i=0;i<2;i++){const s=await page.evaluate(key=>JSON.parse(localStorage.getItem(key)),key);assert.equal(s.objectPhase,expected);assert.equal(s.objectFlowVersion,2);assert.deepEqual(s.answers,{objectAction:'Mijn actie',objectView:'Mijn beeld'});assert.equal(s.associations.length,1);assert.equal(s.objectId,'touw');await page.reload();await page.getByRole('heading',{name:'Nog één ding…',exact:true}).waitFor();}await context.close();
 }
 }finally{if(browser)await browser.close();await new Promise(r=>server.close(r));}
})().catch(e=>{console.error(e);process.exitCode=1;});
