// Optional real Chromium checks; install Playwright + Chromium in the test environment.
const {chromium}=require('playwright'),assert=require('node:assert/strict'),http=require('node:http'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..'),key='associatieruimte.v01';
const server=http.createServer((req,res)=>{const file=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname);if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}fs.readFile(file,(err,data)=>{if(err){res.writeHead(404).end();return;}res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.json':'application/json','.css':'text/css','.webp':'image/webp'})[path.extname(file)]||'application/octet-stream');res.end(data);});});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;try{
 browser=await chromium.launch({args:['--no-sandbox']});const url=`http://127.0.0.1:${server.address().port}/index.html`;
 for(const mobile of [false,true])for(const [route,random] of [['standing',0],['size',0],['size',.9],['dialogue',0]]){
  const context=await browser.newContext({viewport:mobile?{width:390,height:844}:{width:1280,height:900},hasTouch:mobile});
  await context.addInitScript(random=>{Math.random=()=>random;if(!localStorage.getItem('associatieruimte.v01'))localStorage.setItem('associatieruimte.v01',JSON.stringify({stepId:'research',flowVersion:3,originalQuestion:'Vraag',answers:{},associations:['energie','vrijheid','beweging'].map((text,i)=>({id:'word-'+i,text,x:30+i*20,y:30+i*20,size:1,color:'#112233'})),routeId:'animal',imageIds:['image-01','image-02','image-03']}));},random);
  const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(url);const state=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('associatieruimte.v01')));
  await page.getByRole('button',{name:route==='standing'?'Bij een woord gaan staan':route==='size'?'Groot en klein ervaren':'Twee woorden laten spreken',exact:true}).click();await page.getByRole('button',{name:'Verder',exact:true}).click();assert.equal((await state()).stepId,'research');await page.locator('.selection-validation').waitFor();
  const word=id=>page.locator(`.canvas .word[data-id="${id}"]`);
  await word('word-0').click();assert.equal((await state()).research.xId,'word-0');assert.equal(await word('word-0').getAttribute('data-research-role'),'X');
  if(route==='dialogue'){await page.getByRole('button',{name:'Verder',exact:true}).click();assert.equal((await state()).research.yId,null);await word('word-1').click();assert.equal((await state()).research.yId,'word-1');assert.equal(await word('word-1').getAttribute('data-research-role'),'Y');}
  else assert.equal(await page.locator('select').first().inputValue(),'word-0');
  const editId=route==='dialogue'?'word-2':'word-1';await word(editId).click();assert.equal((await state()).research.xId,'word-0');assert.equal((await state()).activeId,editId);const initialSize=(await state()).associations.find(a=>a.id===editId).size;await page.getByRole('button',{name:'Groter',exact:true}).click();assert((await state()).associations.find(a=>a.id===editId).size>initialSize);assert.equal((await state()).associations[0].size,1);await page.getByRole('button',{name:'Kleiner',exact:true}).click();
  await page.getByLabel('Kleur van geselecteerd element',{exact:true}).evaluate(n=>{n.value='#abcdef';n.dispatchEvent(new Event('input',{bubbles:true}));});assert.equal((await state()).associations.find(a=>a.id===editId).color,'#abcdef');assert.equal((await state()).associations[0].color,'#112233');
  await word(editId).scrollIntoViewIfNeeded();const b=await word(editId).boundingBox(),start={x:b.x+b.width/2,y:b.y+b.height/2};
  if(mobile){const cdp=await context.newCDPSession(page);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[start]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:start.x-30,y:start.y-10}]});assert((await word(editId).boundingBox()).x<b.x-5);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await cdp.detach();}
  else{await page.mouse.move(start.x,start.y);await page.mouse.down();await page.mouse.move(start.x-30,start.y-10,{steps:5});assert((await word(editId).boundingBox()).x<b.x-5);await page.mouse.up();}assert.equal((await state()).research.xId,'word-0');
  if(route==='standing'){await page.getByRole('button',{name:'Vanaf dit woord naar een ander woord kijken',exact:true}).click();await word('word-1').click();assert.equal((await state()).research.yId,'word-1');assert.equal(await page.locator('select').nth(1).inputValue(),'word-1');}
  if(route==='dialogue'){await page.getByRole('button',{name:'Andere woorden kiezen',exact:true}).click();await word('word-2').click();await page.locator('select').selectOption('word-0');assert.equal((await state()).research.xId,'word-2');assert.equal((await state()).research.yId,'word-0');}
  else{await page.getByRole('button',{name:'Woord voor de oefening wijzigen',exact:true}).click();await word('word-2').click();assert.equal(await page.locator('select').first().inputValue(),'word-2');await page.locator('select').first().selectOption('word-0');assert.equal((await state()).research.xId,'word-0');}
  const selected=(await state()).research;await page.reload();assert.equal((await state()).research.xId,selected.xId);assert.equal((await state()).research.yId,selected.yId);await page.getByRole('button',{name:'Oefening afronden',exact:true}).click();await page.getByRole('heading',{name:'Kijk opnieuw naar je ruimte',exact:true}).waitFor();assert.deepEqual(errors,[]);await context.close();console.log(`PASS Chromium selection: ${mobile?'touch/mobile':'mouse/desktop'} ${route}/${random}`);
 }
 }finally{if(browser)await browser.close();await new Promise(r=>server.close(r));}
})().catch(e=>{console.error(e);process.exitCode=1;});
