const assert=require('node:assert/strict'),vm=require('node:vm');
const {Element,questions,script,setViewport}=require('./flow.cjs');
const key='associatieruimte.v01';
async function setup(routeId='landscape',viewport='desktop',saved){
 setViewport(viewport==='mobile'?350:872,viewport==='mobile'?380:500);
 const app=new Element('main'),erase=new Element('button'),notice=new Element('p'),storage={};
 storage[key]=JSON.stringify(saved||{step:1,stepId:'imagine',entryType:'Ik zit ergens mee',originalQuestion:'Een eigen beginvraag',answers:{},associations:[],routeId,imageIds:['image-01','image-02','image-03'],selectedImage:null,selectedElement:null,activeId:null,firstSpaceStep:null,research:null});
 let ctx={document:{querySelector:q=>({'#app':app,'#erase':erase,'#storage-notice':notice})[q],createElement:t=>new Element(t)},localStorage:{getItem:k=>storage[k]??null,setItem:(k,v)=>storage[k]=v,removeItem:k=>delete storage[k]},crypto:require('node:crypto').webcrypto,window:{scrollTo(){}},fetch:async()=>({ok:true,json:async()=>questions})};
 const boot=async()=>{ctx={...ctx};vm.createContext(ctx);vm.runInContext(script,ctx);await new Promise(r=>setImmediate(r));};await boot();
 const state=()=>JSON.parse(storage[key]);
 const click=(text,host=app)=>{const b=host.querySelectorAll('button').find(n=>n.textContent===text||n.attrs['aria-label']===text);assert(b,'Button: '+text);b.listeners.click();};
 const form=taking=>app.querySelectorAll('form').find(n=>n.attrs['aria-label']===(taking?'Iets meenemen':'Zelf iets toevoegen'));
 const submit=(taking,text,color)=>{const f=form(taking);assert(f);const input=f.querySelectorAll('input').find(n=>n.attrs.type!=='color');input.value=text;if(color){const c=f.querySelectorAll('input').find(n=>n.attrs.type==='color');c.value=color;c.listeners.input();}f.listeners.submit({preventDefault(){}});};
 const answer=(index,text)=>{const n=app.querySelectorAll('textarea')[index];assert(n);n.value=text;n.listeners.input();};
 return{app,state,click,form,submit,answer,boot,storage,get ctx(){return ctx;}};
}
(async()=>{
 let scenarios=0;
 for(const viewport of ['desktop','mobile'])for(const route of questions.routes){
  const h=await setup(route.id,viewport);const source='  stromend water $& <b>\n mijn eigen zinnen  ';
  assert(h.app.textContent.includes('Je kunt hier woorden of korte zinnen verzamelen'));assert(h.app.querySelector('.takeaway').hidden);assert(h.form(false));assert(!h.form(true));
  h.answer(0,source);assert(!h.app.querySelector('.takeaway').hidden);assert.equal(h.app.querySelector('.takeaway').querySelector('.answer-reference').textContent,`(Eerder schreef je: ‘${source}’)`);assert.equal(h.state().associations.length,0);
  h.click('Iets meenemen');assert(h.form(true));const taking=h.form(true).querySelectorAll('input').find(n=>n.attrs.type!=='color');assert.equal(taking.value,'','The app must never prefill/copy/extract words');assert.equal(taking.attrs['aria-label'],'Wat wil je meenemen?');assert(h.form(false),'Free input must remain alongside taking');
  h.submit(true,'', '#be4466');assert.equal(h.state().associations.length,0);h.submit(true,'stromend water','#be4466');assert.equal(h.state().associations.length,1);assert.equal(h.state().associations[0].text,'stromend water');assert.equal(h.state().answers[route.fields[0].key],source);assert.equal(h.state().associations[0].color,'#be4466');
  await h.boot();assert.equal(h.state().associations.length,1,'Reload must not add a duplicate');assert.equal(h.state().answers[route.fields[0].key],source);
  h.submit(false,'vrijheid','#2288cc');assert.equal(h.state().associations.length,2);assert.equal(h.state().associations[1].text,'vrijheid');assert(!Object.values(h.state().answers).some(answer=>answer.includes('vrijheid')));assert.deepEqual(Object.keys(h.state().associations[0]).sort(),Object.keys(h.state().associations[1]).sort(),'Both types have the same element schema, no automatic category/source');
  h.answer(2,'  Een later antwoord  ');assert.equal(h.app.querySelector('.takeaway').querySelector('.answer-reference').textContent,'(Eerder schreef je: ‘  Een later antwoord  ’)');h.click('Niet nu');assert(h.app.querySelector('.takeaway').hidden);assert(h.form(false));h.answer(0,'Een nieuw antwoord in hetzelfde scherm');assert(h.app.querySelector('.takeaway').hidden,'Skip must remain respected while typing on this screen');
  h.click('Verder');assert(h.app.querySelector('.takeaway').hidden);h.click('Kies beeld 1');h.answer(0,'Mijn eigen beeldassociatie');assert(!h.app.querySelector('.takeaway').hidden);assert.equal(h.app.querySelector('.takeaway').querySelector('.answer-reference').textContent,'(Eerder schreef je: ‘Mijn eigen beeldassociatie’)');h.click('Iets meenemen');assert.equal(h.form(true).querySelector('input').value,'');h.click('Niet nu');h.click('Verder');
  assert.equal(h.app.querySelector('h1').textContent,'Jouw Associatieruimte');assert(!h.app.querySelector('.takeaway'));
  for(const text of ['stromend water','vrijheid']){const word=h.app.querySelectorAll('.word').find(n=>n.textContent===text);assert(word);word.listeners.click();const size=parseFloat(word.style.fontSize),x=parseFloat(word.style.left);h.click('Groter');assert(parseFloat(word.style.fontSize)>size);h.click('Kleiner');h.click('→');assert(parseFloat(word.style.left)>x);word.listeners.pointerdown({button:0,clientX:100,clientY:100,pointerId:1});const start=parseFloat(word.style.left);word.listeners.pointermove({clientX:120,clientY:115});assert(parseFloat(word.style.left)>start);word.listeners.pointerup();const color=h.app.querySelectorAll('input').find(n=>n.attrs['aria-label']==='Kleur van geselecteerd element');color.value='#112233';color.listeners.input();assert.equal(word.style.backgroundColor,'#112233');}
  h.click('Verder');assert.equal(h.app.querySelector('.choices').querySelectorAll('button').length,3,'Two text elements allow relational exercises');assert(h.app.querySelectorAll('button').some(n=>n.textContent==='Twee woorden laten spreken'));
  await h.boot();assert.equal(h.state().associations.length,2);assert.equal(h.state().associations[0].color,'#112233');scenarios++;
 }
 for(const viewport of ['desktop','mobile']){
  const h=await setup('landscape',viewport);h.answer(0,'Een eigen antwoord');h.click('Niet nu');h.click('Verder');h.click('Verder');assert.equal(h.app.querySelector('h1').textContent,'Terug naar je beginvraag');assert(!h.app.querySelector('select'));h.click('Verder');h.click('Verder');assert.equal(h.app.querySelector('h1').textContent,'Dit ontstond er onderweg');assert.equal(h.state().associations.length,0);
  const single=await setup('animal',viewport);single.answer(0,'Een egel');single.click('Iets meenemen');single.submit(true,'egel');assert(!('color' in single.state().associations[0]));single.click('Verder');single.click('Verder');single.click('Verder');assert.equal(single.app.querySelector('.choices').querySelectorAll('button').length,2);assert(!single.app.querySelectorAll('button').some(n=>n.textContent==='Twee woorden laten spreken'));await single.boot();assert.equal(single.state().associations.length,1);
  const images=await setup('movement',viewport);images.click('Verder');images.click('Kies beeld 1');images.answer(0,'  Het beeld doet me denken aan water.  ');images.click('Iets meenemen');images.submit(true,'iets uit het beeld');assert.equal(images.state().associations.length,1);assert.equal(images.state().answers.imageAssociation,'  Het beeld doet me denken aan water.  ');await images.boot();assert.equal(images.state().associations.length,1);
 }
 // Existing sessions with shapes, colors and words remain byte-for-byte intact on resume.
 const legacy={step:1,entryType:'Ik zit ergens mee',originalQuestion:'oud',answers:{landscape:'eerder antwoord'},associations:[{id:'old',text:'rust',x:35,y:40,size:1.3,color:'#112233'},{id:'shape',shape:'circle',text:'',x:50,y:50,size:1,color:'#445566'}],routeId:'landscape',imageIds:['image-01','image-02','image-03']};const resumed=await setup('landscape','desktop',legacy);assert.deepEqual(resumed.state().associations,legacy.associations);assert.deepEqual(resumed.state().answers,legacy.answers);assert(!resumed.form(true));
 console.log(`PASS take-away: ${scenarios} route/viewport scenarios; plus optional zero-word finish, one/two-word suitability, taking from images, unchanged answers, free additions, identical canvas behavior, no reload duplicates, blank input and legacy sessions`);
})().catch(e=>{console.error(e);process.exitCode=1;});
